//
//  Workspace.swift
//  Config
//
//  Created by 김지수 on 8/17/24.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "three-days-iOS",
    projects: [
        "Projects/App",
        "Projects/Core",
        "Projects/DesignSystem",
        "Projects/Features"
    ],
    schemes: [
        .scheme(
            name: "three-days-dev",
            buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: AppConfig.dev.appName)]),
            runAction: .runAction(
                configuration: .debug,
                arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
            ),
            archiveAction: .archiveAction(configuration: .configuration("Staging")),
            profileAction: .profileAction(configuration: .debug),
            analyzeAction: .analyzeAction(configuration: .debug)
        ),
        .scheme(
            name: "three-days-prod",
            buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: AppConfig.prod.appName)]),
            runAction: .runAction(
                configuration: .release,
                arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
            ),
            archiveAction: .archiveAction(configuration: .release),
            profileAction: .profileAction(configuration: .release),
            analyzeAction: .analyzeAction(configuration: .release)
        ),
        .scheme(
            name: "three-days-UnitTest",
            testAction: .targets(
                [
                    .target(.coreKit),
                    .target(.designCore),
                    .target(.signUp)
                ]
            )
        ),
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
