name: unitTest

on:
  pull_request:

jobs:
  run-unitTest:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Install Mise
      run: |
          curl https://mise.run | sh
          mise install
    - name: Create Secret.swift file
      run: |
          echo '${{ secrets.SECRET_SWIFT }}' > ./Projects/Core/CoreKit/Sources/Secret.swift
    - name: Install Tuist dependencies
      run: mise x -- tuist install
      
    - name: Generate Xcworkspace
      run: mise x -- tuist generate
      
    - name: Run unit tests
      run: |
        set -o pipefail && xcodebuild test \
          -scheme three-days-UnitTest \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          | tee result.log
        if grep -q "** TEST FAILED **" result.log; then
          exit 1
        fi
      continue-on-error: false

    - name: Failure notification to Discord
      if: failure()
      run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": null, \"embeds\": [{\"title\": \"iOS 유닛 테스트 실패..?\", \"description\": \"Actor: ${{ github.actor }}\nBranch: ${{ github.head_ref }}\nCommit: ${{ github.event.pull_request.head.sha }}\n\n💥 잉?!\", \"color\": 16711741}]}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
