name: unitTest

on:
  pull_request:

jobs:
  run-unitTest:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Mise
      run: |
          curl https://mise.run | sh
          mise install
    - name: Create Secret.swift file
      run: |
          echo '${{ secrets.SECRET_SWIFT }}' > ./Projects/Core/CoreKit/Sources/Secret.swift
    - name: Install Tuist dependencies
      run: mise x -- tuist install
      
    - name: Generate Xcworkspace
      run: mise x -- tuist generate
      
    - name: Run unit tests
      run: |
        xcodebuild test -scheme three-days-UnitTest -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' | tee result.log
      continue-on-error: true
